FROM php-phalcon:7.3-fpm-alpine

WORKDIR /www/html/api

ARG DB_USER=meglms
ARG DB_HOST=mysql
ARG DB_PASSWORD=meglms#123
ARG DB_DATABASE=meglms

ENV DB_USER=${DB_USER}
ENV DB_HOST=${DB_HOST}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_DATABASE=${DB_DATABASE}

COPY ./src /www/html/api

CMD ["php-fpm", "-F"]


EXPOSE 9000